# -*- coding: utf-8 -*-
"""Data_Understand.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Edna-soso/DataAnalysis_Project/blob/main/Data_Understand/Data_Understand.ipynb
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/python_OP/OnlineRetail.csv', encoding = 'unicode_escape')

print(data.shape)

class data_understand:
  def __init__(self, data):
    self.data = data
  def basic_info(self):
    while(True):
      choice= int(input('*'*15+"Basic_Info"+ '*'*15+"\n1.The first five rows\n2.List colunms\n3.Sum of NaN values\n4.Showing Basics Statistics\n5.Displaying Data Types\n6.Exis\n"))
      if choice == 1:
        print(data.head())
      elif choice == 2:
        print(list(data.columns))
      elif choice ==3:
        print(data.isna().sum())   
      elif choice ==4:
        print(data.describe())   
      elif choice ==5:
        print(data.info()) 
      else:
        break

  def count_customer_country(self):
    country_data = data[['Country','CustomerID']].drop_duplicates()
    return country_data.groupby(['Country']).agg({'CustomerID' : 'count'}).sort_values('CustomerID',ascending = False).reset_index().rename(columns = {'CustomerID':'CustomerID Count'})
    
  def count_country(self):
    return data['Country'].value_counts()

df=data_understand(data)
df.basic_info()

